name    'openstack-hyper-v-windows_chrome'
version '0.0.1'
source 'https://github.com/openstack-hyper-v/puppet-windows_chrome.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing Chrome on the Windows Platform'
description 'Puppet module for installing Chrome on the Windows Platform'
project_page 'https://github.com/openstack-hyper-v/puppet-windows_chrome'
dependency 'joshcooper/powershell'
dependency 'openstack-hyper-v/windows_common'
dependency 'basti1302/windows_path'
